### PR TITLE
fix Issue #1 and some other improvements

### PR DESCRIPTION
**Pull request by Buxxter**
+ myStrip function added to remove unprintable symbols from hostname (Issue #1)
+ "Clear old static ..." and "Create or update static DNS" updated with myStrip
+ Records added with this script marked with comment
+ "Clear old static ..." clearing only records marked with comment
+ Create or update DNS record only for "bound" and Enabled leases

### CODE REVIEW

**Comment by Tolaris** [comment]
Feel free to remove the old lines you commented out. Thanks!

**Comment by Buxxter** [comment]
My first pull-request, sorry :-)
Thought it will be easier to review. Don't know how the merge process looks like (

**Comment by Buxxter** [comment]
Maybe you can help to fix line 15? Can't make this thing works

**Comment by Tolaris** [comment]
No worries. Diffs are easy to revert because they remain in history, so keeping old lines doesn't usually matter.

Sorry, I can't help with line 15. I don't use DHCP+DNS on Mikrotik any longer. You are welcome to take over this repository.

**Pull request merged**
